// URL konstantalari. Locale prefiksisiz — next-intl navigation (Link, useRouter)
// avtomatik ravishda /uz, /ru, /en, /kz prefiksini qo'shadi.
export const paths = {
  welcome: '/',
  role: '/role',
  login: '/login',
  loginCode: '/login-code',
  forgotPassword: '/forgot-password',
  registrDoc: '/register_doc',
  registerPat: '/register_pat',
  patient: '/patients',
  patientProfile: '/patients/:id',
  profile: '/profile',
  editProfile: '/profile/edit',
  menu: '/menu',
  settings: '/settings',
  appointments: '/appointments',
  analytics: '/analytics',
  chats: '/chats',
  chatDetail: '/chats/:id',
  patientHome: '/home',
  patientCalendar: '/calendar',
  patientHistory: '/history',
  patientProfileSettings: '/profile_pat',
  patientAppointmentDetail: '/appointment/:id',
  patientChats: '/patient/chats',
  patientChatDetail: '/patient/chats/:id',
  doctors: '/doctors',
  specialties: '/specialties',
  notifications: '/notifications',
  patientNotifications: '/patient/notifications',
  booking: '/booking',
  checkupPreview: '/booking/checkup-preview',
  myDentist: '/my-dentist',
  patientChatProfile: '/patient/chats/:id/profile',
  treatments: '/treatments',
  doctorServices: '/doctor-services',
  doctorCases: '/doctor-cases',
  videoCall: '/video-call',
  searchResults: '/search',
} as const;
